---
# Test namespace
apiVersion: v1
kind: Namespace
metadata:
  name: test-app
  labels:
    name: test-app
---
# Service Account for test user
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-user
  namespace: test-app
---
# Role for test user
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test-app
  name: test-user-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "create", "update", "delete"]
---
# RoleBinding for test user
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-user-binding
  namespace: test-app
subjects:
- kind: ServiceAccount
  name: test-user
  namespace: test-app
roleRef:
  kind: Role
  name: test-user-role
  apiGroup: rbac.authorization.k8s.io
---
# Test pod
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: test-app
  labels:
    app: test-app
spec:
  serviceAccountName: test-user
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
---
# Test service
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: test-app
spec:
  selector:
    app: test-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP 